let modelsJson = [
    {id:1, name: ' Pacote Simples', img:'img pacotes/Pacote Simples.png', price:[80.00, 95.00, 115.00], sizes:['Mensagem Automática', 'Mensagem Gravada', 'Incluir Kit Rei ou Rainha'], description:'Esse pacote inclui: Carro (Decorado) com Mensagem Automática + Música'},
    {id:2, name:' Pacote Aniversário', img:'img pacotes/Pacote Aniversario.png', price:[100.00, 115.00, 150.00], sizes:['Mensagem Automática', 'Mensagem Gravada', 'Incluir Kit Rei ou Rainha'], description:'Esse pacote inclui: Carro (Decorado) com Mensagem de Aniversário + Mensagem de Voz + Música'},
    {id:3, name:' Pacote Apaixonado', img:'img pacotes/Pacote Apaixonado.png', price:[150.00, 165.00, 200.00], sizes:['Mensagem Automática', 'Mensagem Gravada', 'Incluir Pétalas de Rosa e Bastão de Fumaça'], description:'Esse pacote inclui: Carro (Decorado) com Mensagem Apaixonada + Mensagem de voz + Tapete Vermelho + Música + Kit Rei ou Rainha'},
    {id:4, name:' Pacote Liga Pra Mim', img:'img pacotes/Pacote Liga Pra Mim.png', price:[25.00, 30.00, 40.00], sizes:['Pacote Sem Alteração', 'Incluir Outra Mensagem', 'Incluir Entrega de Lembrança'], description:'Esse pacote inclui: Mensagem de Voz Gravada + Música'},
    {id:5, name:' Pacote Casa Comigo', img:'img pacotes/Pacote Casa Comigo.png', price:[130.00, 150.00, 180.00], sizes:['Mensagem Automática', 'Mensagem Gravada', 'Incluir Kit Rei ou Rainha'], description:'Esse pacote inclui: Carro (Decorado) + Mensagem de Voz + Cantor + Tapete Vermelho + Kit Rei ou Rainha + Brinde (Pétalas de Rosa ou Bouquet)'},
    {id:6, name:' Pacote Luxuoso', img:'img pacotes/Pacote Luxuoso.png', price:[200.00, 230.00, 280.00], sizes:['Mensagem Automática', 'Mensagem Gravada', 'Incluir Cantor'], description:'Esse pacote inclui: Limousine (Decoração Interna e Externa) + Mensagem de Voz + Tapete Vermelho + Kit Rei ou Rainha + Música + Microfone + Brinde (Pétalas de Rosa ou Bouquet)'},
    {id:7, name:' Pacote Recadinho', img:'img pacotes/Pacote Recadinho.png', price:[10.00, 15.00, 25.00], sizes:['Pacote Sem Alteração', 'Incluir Mensagem de Voz', 'Incluir Entrega de Lembrança'], description:'Esse pacote inclui uma mensagem de texto com fundo musical'},
    {id:8, name:' Pacote Casamento', img:'img pacotes/Pacote Casamento.png', price:[250.00, 280.00, 300.00], sizes:['Pacote Sem Alteração', 'Incluir Mensagem de Voz', 'Incluir Entrega de Lembrança'], description:'Limousine (Decoração Interna e Externa) + Mensagem de Voz + Tapete Vermelho + Kit Rei ou Rainha + Música + Microfone + Cantor + Brinde (Pétalas de Rosa ou Bouquet)'}
];